package View;

import Controller.VisitanteController;
import Model.Visitante;
import java.text.SimpleDateFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author rodri
 */
public class CadastroVisitante extends javax.swing.JFrame {

    /**
     * Creates new form CadastroVisitante
     */
    public CadastroVisitante() {
        initComponents();
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbTipoVisitanteCad = new javax.swing.JComboBox<>();
        txtNomeCad = new javax.swing.JTextField();
        txtRgCad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botbuscaMoradorVisCad = new javax.swing.JButton();
        cadastrarVisitante = new javax.swing.JButton();
        excluirVisitante = new javax.swing.JButton();
        alterarVisitante = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelInvisivel = new javax.swing.JLabel();
        ftxtDataNascCad = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCFP - CADASTRO DE VISITANTES");

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Nome:");

        jLabel2.setText("RG:");

        cbTipoVisitanteCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Visitante", "Prestador de Serviço" }));
        cbTipoVisitanteCad.setActionCommand("tipoVisitanteCad");

        txtNomeCad.setName("txtNomeCad"); // NOI18N

        txtRgCad.setName("txtRgCad"); // NOI18N

        jLabel4.setText("Tipo:");

        botbuscaMoradorVisCad.setText("Buscar");
        botbuscaMoradorVisCad.setActionCommand("botBuscaMoradorVAlt");
        botbuscaMoradorVisCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botbuscaMoradorVisCadActionPerformed(evt);
            }
        });

        cadastrarVisitante.setBackground(new java.awt.Color(0, 153, 0));
        cadastrarVisitante.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarVisitante.setText("Cadastrar");
        cadastrarVisitante.setActionCommand("cadastrarVisitante");
        cadastrarVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarVisitanteActionPerformed(evt);
            }
        });

        excluirVisitante.setBackground(new java.awt.Color(204, 0, 0));
        excluirVisitante.setForeground(new java.awt.Color(255, 255, 255));
        excluirVisitante.setText("Excluir");
        excluirVisitante.setActionCommand("excluirVisitante");
        excluirVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirVisitanteActionPerformed(evt);
            }
        });

        alterarVisitante.setBackground(new java.awt.Color(102, 102, 102));
        alterarVisitante.setForeground(new java.awt.Color(255, 255, 255));
        alterarVisitante.setText("Alterar");
        alterarVisitante.setActionCommand("alterarVisitante");
        alterarVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarVisitanteActionPerformed(evt);
            }
        });

        jLabel3.setText("Data de Nasc.:");

        labelInvisivel.setEnabled(false);
        labelInvisivel.setFocusable(false);
        labelInvisivel.setVisible(false);

        try {
            MaskFormatter mascaradata = new MaskFormatter("##/##/####");
            ftxtDataNascCad = new JFormattedTextField(mascaradata);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao iniciar campo data");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRgCad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtDataNascCad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbTipoVisitanteCad, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botbuscaMoradorVisCad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(excluirVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alterarVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrarVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInvisivel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRgCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ftxtDataNascCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoVisitanteCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(botbuscaMoradorVisCad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInvisivel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarVisitante)
                    .addComponent(alterarVisitante)
                    .addComponent(excluirVisitante))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarVisitanteActionPerformed
        String nome = txtNomeCad.getText().toUpperCase();
        String rg = txtRgCad.getText().toUpperCase();
        String dataNascimento = ftxtDataNascCad.getText();
        String tipoVisitante = cbTipoVisitanteCad.getSelectedItem().toString();                
        try {           
            if(nome != null && rg != null && dataNascimento != null && !tipoVisitante.equals("Selecione"))
                VisitanteController.cadastrarVisitante(nome, rg, dataNascimento, tipoVisitante);            
            else 
                throw new Exception("Dados Insuficientes para o Cadastro!");
            JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
            limpaCampos();
        } catch (Exception ex) {                
            JOptionPane.showMessageDialog(null, ex.getMessage());                            
        }
    }//GEN-LAST:event_cadastrarVisitanteActionPerformed

    private void botbuscaMoradorVisCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botbuscaMoradorVisCadActionPerformed
        Visitante visitante = new Visitante();
        SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
        try {
            String rg = txtRgCad.getText().toUpperCase();
            
            if(!rg.isEmpty())         
                visitante = VisitanteController.consultarVisitante(rg);

            txtNomeCad.setText(visitante.getNome());
            txtRgCad.setText(visitante.getRg());
            
            ftxtDataNascCad.setText(data.format(visitante.getDtNascimento()));
            
            switch(visitante.getTipoVisitante()){
                case VISITANTE:
                    cbTipoVisitanteCad.setSelectedIndex(1);
                    break;
                case PRESTADORSERVICO:
                    cbTipoVisitanteCad.setSelectedIndex(2);
                    break;
                default:
                    cbTipoVisitanteCad.setSelectedIndex(0);
                    break;
            }                        
            labelInvisivel.setText(String.valueOf(visitante.getId()));                        
        } catch (Exception ex) {            
            limpaCampos();
            JOptionPane.showMessageDialog(null, ex.getMessage());            
        }
    }//GEN-LAST:event_botbuscaMoradorVisCadActionPerformed

    private void excluirVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirVisitanteActionPerformed
        try {        
            int id = Integer.parseInt(labelInvisivel.getText());
        
            if(id != 0)
                VisitanteController.excluirVisitante(id);
            else{                
                throw new Exception("Visitante não cadastrado!");
            }
            JOptionPane.showMessageDialog(null, "Visitante Excluído com sucesso!");
            limpaCampos();
            } catch (Exception ex) {                
                JOptionPane.showMessageDialog(null, ex.getMessage());                
            }
    }//GEN-LAST:event_excluirVisitanteActionPerformed

    private void alterarVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarVisitanteActionPerformed
        String id = labelInvisivel.getText();
        String nome = txtNomeCad.getText();
        String rg = txtRgCad.getText();
        String dataNascimento = ftxtDataNascCad.getText();
        String tipoVisitante = cbTipoVisitanteCad.getSelectedItem().toString();
        
        if(nome != null && rg != null && dataNascimento!= null && !tipoVisitante.equals("Selecione")){
            try {                
                VisitanteController.alterarVisitante(id,nome, rg, dataNascimento, tipoVisitante);
                JOptionPane.showMessageDialog(null, "Visitante alterado com sucesso!");
                limpaCampos();
            } catch (Exception ex) {                
                 JOptionPane.showMessageDialog(null, ex.getMessage());                
            }
        }
    }//GEN-LAST:event_alterarVisitanteActionPerformed

    private void limpaCampos(){
        labelInvisivel.setText("");
        txtNomeCad.setText("");
        txtRgCad.setText("");
        cbTipoVisitanteCad.setSelectedIndex(0);
        ftxtDataNascCad.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVisitante().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarVisitante;
    private javax.swing.JButton botbuscaMoradorVisCad;
    private javax.swing.JButton cadastrarVisitante;
    private javax.swing.JComboBox<String> cbTipoVisitanteCad;
    private javax.swing.JButton excluirVisitante;
    private javax.swing.JFormattedTextField ftxtDataNascCad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInvisivel;
    private javax.swing.JTextField txtNomeCad;
    private javax.swing.JTextField txtRgCad;
    // End of variables declaration//GEN-END:variables
}
