/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.VisitanteController;
import Model.Visitante;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class CadastroVisitante extends javax.swing.JFrame {

    /**
     * Creates new form CadastroVisitante
     */
    public CadastroVisitante() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tipoVisitanteCad = new javax.swing.JComboBox<>();
        nomeVisitanteCad = new javax.swing.JTextField();
        rgVisitanteCad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botbuscaMoradorVisCad = new javax.swing.JButton();
        cadastrarVisitante = new javax.swing.JButton();
        excluirVisitante = new javax.swing.JButton();
        alterarVisitante = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dataNascimentoCadVist = new javax.swing.JFormattedTextField();
        labelInvisivel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCFP - CADASTRO DE VISITANTES");

        jLabel1.setText("Nome:");

        jLabel2.setText("RG:");

        tipoVisitanteCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Visitante", "Prestador de Serviço" }));
        tipoVisitanteCad.setActionCommand("tipoVisitanteCad");

        nomeVisitanteCad.setName("nomeVisitanteCad"); // NOI18N

        rgVisitanteCad.setName("rgVisitanteCad"); // NOI18N

        jLabel4.setText("Tipo:");

        botbuscaMoradorVisCad.setText("Buscar");
        botbuscaMoradorVisCad.setActionCommand("botBuscaMoradorVAlt");
        botbuscaMoradorVisCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botbuscaMoradorVisCadMouseClicked(evt);
            }
        });

        cadastrarVisitante.setBackground(new java.awt.Color(0, 153, 0));
        cadastrarVisitante.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarVisitante.setText("Cadastrar");
        cadastrarVisitante.setActionCommand("cadastrarVisitante");
        cadastrarVisitante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarVisitanteMouseClicked(evt);
            }
        });

        excluirVisitante.setBackground(new java.awt.Color(204, 0, 0));
        excluirVisitante.setForeground(new java.awt.Color(255, 255, 255));
        excluirVisitante.setText("Excluir");
        excluirVisitante.setActionCommand("excluirVisitante");
        excluirVisitante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirVisitanteMouseClicked(evt);
            }
        });

        alterarVisitante.setBackground(new java.awt.Color(102, 102, 102));
        alterarVisitante.setForeground(new java.awt.Color(255, 255, 255));
        alterarVisitante.setText("Alterar");
        alterarVisitante.setActionCommand("alterarVisitante");
        alterarVisitante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarVisitanteMouseClicked(evt);
            }
        });

        jLabel3.setText("Data de Nasc.:");

        labelInvisivel.setText("Não estou aqui !");
        labelInvisivel.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeVisitanteCad, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rgVisitanteCad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataNascimentoCadVist))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tipoVisitanteCad, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botbuscaMoradorVisCad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(excluirVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alterarVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrarVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelInvisivel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeVisitanteCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rgVisitanteCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(dataNascimentoCadVist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoVisitanteCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(botbuscaMoradorVisCad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInvisivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarVisitante)
                    .addComponent(alterarVisitante)
                    .addComponent(excluirVisitante))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarVisitanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarVisitanteMouseClicked
        
        String nome = nomeVisitanteCad.getSelectedText();
        String rg = rgVisitanteCad.getSelectedText();
        String dataNascimento = dataNascimentoCadVist.getSelectedText();
        String tipoVisitante = tipoVisitanteCad.getSelectedItem().toString();
        
        if(!nome.isEmpty() && !rg.isEmpty() && !dataNascimento.isEmpty() && !tipoVisitante.isEmpty()){
            
            try {
                
                VisitanteController.cadastrarVisitante(nome, rg, dataNascimento, tipoVisitante);
                
            } catch (Exception ex) {
                
                JOptionPane.showMessageDialog(null, ex.getMessage());
                
            }
        }
    }//GEN-LAST:event_cadastrarVisitanteMouseClicked

    private void alterarVisitanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarVisitanteMouseClicked
        String nome = nomeVisitanteCad.getSelectedText();
        String rg = rgVisitanteCad.getSelectedText();
        String dataNascimento = dataNascimentoCadVist.getSelectedText();
        String tipoVisitante = tipoVisitanteCad.getSelectedItem().toString();
        
        if(!nome.isEmpty() && !rg.isEmpty() && !dataNascimento.isEmpty() && !tipoVisitante.isEmpty()){
            
            try {
                
                VisitanteController.alterarVisitante(nome, rg, nome, tipoVisitante);
                
            } catch (Exception ex) {
                
                 JOptionPane.showMessageDialog(null, ex.getMessage());
                
            }
        }
    }//GEN-LAST:event_alterarVisitanteMouseClicked

    private void excluirVisitanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirVisitanteMouseClicked
       
        try {
        
            int id = Integer.parseInt(labelInvisivel.getText());
        
            if(id == 0)
                VisitanteController.excluirVisitante(id);
                
            } catch (Exception ex) {
                
                JOptionPane.showMessageDialog(null, ex.getMessage());
                
            }
    }//GEN-LAST:event_excluirVisitanteMouseClicked

    private void botbuscaMoradorVisCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botbuscaMoradorVisCadMouseClicked
        
        Visitante visitante = new Visitante();
        
        try {
            String rg = rgVisitanteCad.getText();
            
            if(!rg.isEmpty())         
            visitante = VisitanteController.consultarVisitante(rg);

            nomeVisitanteCad.setText(visitante.getNome());
            rgVisitanteCad.setText(visitante.getRg());
            dataNascimentoCadVist.setText(visitante.getDtNascimento().toString());
            tipoVisitanteCad.setSelectedItem(visitante.getTipoVisitante());
            labelInvisivel.setText(String.valueOf(visitante.getId()));
            
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, ex.getMessage());
            
        } 
    }//GEN-LAST:event_botbuscaMoradorVisCadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVisitante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarVisitante;
    private javax.swing.JButton botbuscaMoradorVisCad;
    private javax.swing.JButton cadastrarVisitante;
    private javax.swing.JFormattedTextField dataNascimentoCadVist;
    private javax.swing.JButton excluirVisitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInvisivel;
    private javax.swing.JTextField nomeVisitanteCad;
    private javax.swing.JTextField rgVisitanteCad;
    private javax.swing.JComboBox<String> tipoVisitanteCad;
    // End of variables declaration//GEN-END:variables
}
