/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MoradorController;
import Model.DAO.DAOBloco;
import Model.Morador;
import java.text.SimpleDateFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author rodri
 */
public class CadastroMorador extends javax.swing.JFrame {

    /**
     * Creates new form CadastroMorador
     */
    public CadastroMorador() throws Exception{
        initComponents();
        this.setResizable(false);            
        carregaCbBloco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeCad = new javax.swing.JTextField();
        txtNumeroApCad = new javax.swing.JTextField();
        txtCodEstacionamentoCad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRgCad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buscaMoradorCad = new javax.swing.JButton();
        cadastrarMorador = new javax.swing.JButton();
        alterarMorador = new javax.swing.JButton();
        excluirMorador = new javax.swing.JButton();
        fTxtDtNasc = new javax.swing.JFormattedTextField();
        cbBloco = new javax.swing.JComboBox<>();
        lblIdMorador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCFP - CADASTRO DE MORADORES");
        setMaximumSize(new java.awt.Dimension(493, 240));

        jLabel1.setText("Nome:");

        jLabel2.setText("Bloco:");

        jLabel3.setText("Nº Apartamento:");

        jLabel4.setText("Cod Estacionamento:");

        txtNomeCad.setName("txtNomeCad"); // NOI18N

        txtNumeroApCad.setName("numeroApartamentoCad"); // NOI18N

        txtCodEstacionamentoCad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCodEstacionamentoCad.setName("codigoEstacionamento"); // NOI18N

        jLabel5.setText("RG:");

        jLabel6.setText("Data de Nasc.:");

        buscaMoradorCad.setText("Buscar");
        buscaMoradorCad.setActionCommand("botBuscarMoradorAlt");
        buscaMoradorCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaMoradorCadActionPerformed(evt);
            }
        });

        cadastrarMorador.setBackground(new java.awt.Color(0, 153, 0));
        cadastrarMorador.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarMorador.setText("Cadastrar");
        cadastrarMorador.setActionCommand("cadastrarMorador");
        cadastrarMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarMoradorActionPerformed(evt);
            }
        });

        alterarMorador.setBackground(new java.awt.Color(102, 102, 102));
        alterarMorador.setForeground(new java.awt.Color(255, 255, 255));
        alterarMorador.setText("Alterar");
        alterarMorador.setActionCommand("alterarMorador");
        alterarMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarMoradorActionPerformed(evt);
            }
        });

        excluirMorador.setBackground(new java.awt.Color(204, 0, 0));
        excluirMorador.setForeground(new java.awt.Color(255, 255, 255));
        excluirMorador.setText("Excluir");
        excluirMorador.setActionCommand("excluirMorador");
        excluirMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirMoradorActionPerformed(evt);
            }
        });

        try {
            MaskFormatter mascaradata = new MaskFormatter("##/##/####");
            fTxtDtNasc = new JFormattedTextField(mascaradata);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao iniciar campo data");
        }

        cbBloco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        lblIdMorador.setText("jLabel7");
        lblIdMorador.setVisible(false);
        lblIdMorador.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(excluirMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(alterarMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtRgCad, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                            .addComponent(cbBloco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cadastrarMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtNumeroApCad)
                                    .addComponent(buscaMoradorCad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fTxtDtNasc)))
                            .addComponent(txtNomeCad)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodEstacionamentoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdMorador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRgCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(fTxtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroApCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodEstacionamentoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaMoradorCad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirMorador)
                    .addComponent(alterarMorador)
                    .addComponent(cadastrarMorador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIdMorador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaMoradorCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaMoradorCadActionPerformed
        SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy");
        try {
            Morador morador = MoradorController.consultarMorador(txtRgCad.getText());
            lblIdMorador.setText(Integer.toString(morador.getId()));
            txtNomeCad.setText(morador.getNome());
            txtRgCad.setText(morador.getRg());
            cbBloco.setSelectedItem(morador.getBloco());
            txtNumeroApCad.setText(String.valueOf(morador.getnApt()));
            txtCodEstacionamentoCad.setText(Integer.toString(morador.getCodEstacionamento()));
            fTxtDtNasc.setText(data.format(morador.getDtNascimento()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_buscaMoradorCadActionPerformed

    private void cadastrarMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarMoradorActionPerformed
        try {
            MoradorController.cadastrarMorador(txtNomeCad.getText().trim(), fTxtDtNasc.getText().trim(), txtRgCad.getText().trim(), cbBloco.getSelectedItem().toString().trim(), txtNumeroApCad.getText().trim(), txtCodEstacionamentoCad.getText().trim());
            JOptionPane.showMessageDialog(null, "Morador Cadastrado com sucesso!");
            limpaCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cadastrarMoradorActionPerformed

    private void alterarMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarMoradorActionPerformed
        try {
            MoradorController.alterarMorador(lblIdMorador.getText(),txtNomeCad.getText().trim(), fTxtDtNasc.getText().trim(), txtRgCad.getText().trim(), cbBloco.getSelectedItem().toString().trim(), txtNumeroApCad.getText().trim(), txtCodEstacionamentoCad.getText().trim());
            JOptionPane.showMessageDialog(null, "Morador alterado com sucesso!");
            limpaCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_alterarMoradorActionPerformed

    private void excluirMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirMoradorActionPerformed
        try {
            MoradorController.excluirMorador(lblIdMorador.getText());
            JOptionPane.showMessageDialog(null, "Morador excluído com sucesso!");
            limpaCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_excluirMoradorActionPerformed

    private void limpaCampos() throws Exception {
        txtCodEstacionamentoCad.setText("");
        txtNomeCad.setText("");
        txtNumeroApCad.setText("");
        txtRgCad.setText("");
        cbBloco.setSelectedIndex(0);
        fTxtDtNasc.setText("");        
    }

    private void carregaCbBloco() {
        try {
            for (String item : DAOBloco.buscaBlocos()) {
                cbBloco.addItem(item);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMorador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMorador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMorador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMorador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroMorador().setVisible(true);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarMorador;
    private javax.swing.JButton buscaMoradorCad;
    private javax.swing.JButton cadastrarMorador;
    private javax.swing.JComboBox<String> cbBloco;
    private javax.swing.JButton excluirMorador;
    private javax.swing.JFormattedTextField fTxtDtNasc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIdMorador;
    private javax.swing.JTextField txtCodEstacionamentoCad;
    private javax.swing.JTextField txtNomeCad;
    private javax.swing.JTextField txtNumeroApCad;
    private javax.swing.JTextField txtRgCad;
    // End of variables declaration//GEN-END:variables
}
