/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LogEntradaController;
import Controller.MoradorController;
import Controller.VisitanteController;
import Model.DAO.DAOBloco;
import Model.DAO.DAOLogEntrada;
import Model.LogEntrada;
import Model.Morador;
import Model.Visitante;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodri
 */
public class SCFP extends javax.swing.JFrame {
    
    /**
     * Creates new form SCFP
     */
    public SCFP() throws Exception {
        initComponents();
        cboxTipoVisitanteLog.requestFocus();
        
        carregaCbBloco();        
        carregaJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeVisitanteLog = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRgVisitanteLog = new javax.swing.JTextField();
        cboxTipoVisitanteLog = new javax.swing.JComboBox<>();
        btnBuscaVisitanteLog = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detalheVisitanteLog = new javax.swing.JTextArea();
        txtnAptLog = new javax.swing.JTextField();
        btnLiberarVisitante = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gridLog = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        cboxBloco = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNomeMorador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCadastroVisitante = new javax.swing.JMenuItem();
        menuCadastroMorador = new javax.swing.JMenuItem();
        menuCadastroFuncionario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCFP - Sistema de Controle de Fluxo de Pessoas");
        setMinimumSize(new java.awt.Dimension(790, 295));

        jLabel1.setText("Visitante* :");

        jLabel2.setText("Tipo* :");

        jLabel3.setText("Nome do Morador:");

        txtNomeVisitanteLog.setForeground(new java.awt.Color(0, 0, 0));
        txtNomeVisitanteLog.setName("txtNomeVisitanteLog"); // NOI18N
        txtNomeVisitanteLog.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        txtNomeVisitanteLog.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeVisitanteLogFocusLost(evt);
            }
        });
        txtNomeVisitanteLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeVisitanteLogMouseClicked(evt);
            }
        });
        txtNomeVisitanteLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeVisitanteLogActionPerformed(evt);
            }
        });

        jLabel4.setText("RG* :");

        txtRgVisitanteLog.setName("txtRgVisitanteLog"); // NOI18N

        cboxTipoVisitanteLog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Visitante", "Prestador de Serviço" }));
        cboxTipoVisitanteLog.setActionCommand("visitanteDescricaolog");
        cboxTipoVisitanteLog.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxTipoVisitanteLogItemStateChanged(evt);
            }
        });

        btnBuscaVisitanteLog.setText("Buscar");
        btnBuscaVisitanteLog.setActionCommand("buscarRgVisitante");
        btnBuscaVisitanteLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaVisitanteLogActionPerformed(evt);
            }
        });

        detalheVisitanteLog.setColumns(20);
        detalheVisitanteLog.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        detalheVisitanteLog.setForeground(new java.awt.Color(0, 0, 0));
        detalheVisitanteLog.setRows(5);
        detalheVisitanteLog.setName("campoDescriçãoServico"); // NOI18N
        detalheVisitanteLog.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                detalheVisitanteLogFocusLost(evt);
            }
        });
        detalheVisitanteLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detalheVisitanteLogMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(detalheVisitanteLog);

        txtnAptLog.setForeground(new java.awt.Color(0, 0, 0));
        txtnAptLog.setName("txtnAptLog"); // NOI18N
        txtnAptLog.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnAptLogFocusLost(evt);
            }
        });
        txtnAptLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnAptLogMouseClicked(evt);
            }
        });

        btnLiberarVisitante.setText("Liberar Visitante");
        btnLiberarVisitante.setActionCommand("okLog");
        btnLiberarVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarVisitanteActionPerformed(evt);
            }
        });

        gridLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Visitante", "Descrição", "Data/Hora", "A Visitar"
            }
        ));
        gridLog.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        gridLog.setName("gridLog"); // NOI18N
        jScrollPane2.setViewportView(gridLog);

        cboxBloco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        jLabel5.setText("Bloco: ");

        jLabel6.setText("Nº Apt:");

        txtNomeMorador.setForeground(new java.awt.Color(0, 0, 0));
        txtNomeMorador.setName("txtnAptLog"); // NOI18N
        txtNomeMorador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeMoradorFocusLost(evt);
            }
        });
        txtNomeMorador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeMoradorMouseClicked(evt);
            }
        });
        txtNomeMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMoradorActionPerformed(evt);
            }
        });

        jLabel7.setText("Descrição da Visita* :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtRgVisitanteLog, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cboxTipoVisitanteLog, javax.swing.GroupLayout.Alignment.LEADING, 0, 152, Short.MAX_VALUE)
                                        .addComponent(btnBuscaVisitanteLog))
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtNomeVisitanteLog, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeMorador)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtnAptLog, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLiberarVisitante)
                                    .addComponent(cboxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeVisitanteLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboxTipoVisitanteLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtRgVisitanteLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscaVisitanteLog))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeMorador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnAptLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cboxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLiberarVisitante)
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Cadastros");

        menuCadastroVisitante.setText("Visitante");
        menuCadastroVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroVisitanteActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastroVisitante);
        menuCadastroVisitante.getAccessibleContext().setAccessibleParent(menuCadastroVisitante);

        menuCadastroMorador.setText("Morador");
        menuCadastroMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroMoradorActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastroMorador);

        menuCadastroFuncionario.setText("Funcionario");
        menuCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastroFuncionario);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroVisitanteActionPerformed
        new CadastroVisitante().setVisible(true);
    }//GEN-LAST:event_menuCadastroVisitanteActionPerformed

    private void menuCadastroMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroMoradorActionPerformed
        try {
            new CadastroMorador().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível carregar o cadastro de moradores");
        }
    }//GEN-LAST:event_menuCadastroMoradorActionPerformed

    private void menuCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroFuncionarioActionPerformed
        new CadastroFuncionario().setVisible(true);
    }//GEN-LAST:event_menuCadastroFuncionarioActionPerformed

    private void txtNomeMoradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMoradorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMoradorMouseClicked

    private void txtNomeMoradorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeMoradorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMoradorFocusLost

    private void btnLiberarVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarVisitanteActionPerformed
        try {
            LogEntradaController.cadastrarLog(txtRgVisitanteLog.getText(), detalheVisitanteLog.getText(), new Date(), txtNomeMorador.getText(), cboxBloco.getSelectedItem().toString(),txtnAptLog.getText());
            JOptionPane.showMessageDialog(null, "Visitante Liberado!");

            carregaJTable();

            txtNomeVisitanteLog.setText("");
            cboxTipoVisitanteLog.setSelectedIndex(0);
            txtRgVisitanteLog.setText("");
            detalheVisitanteLog.setText("");
            txtNomeMorador.setText("");
            cboxBloco.setSelectedIndex(0);
            txtnAptLog.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnLiberarVisitanteActionPerformed

    private void txtnAptLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnAptLogMouseClicked

    }//GEN-LAST:event_txtnAptLogMouseClicked

    private void txtnAptLogFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnAptLogFocusLost

    }//GEN-LAST:event_txtnAptLogFocusLost

    private void detalheVisitanteLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detalheVisitanteLogMouseClicked

    }//GEN-LAST:event_detalheVisitanteLogMouseClicked

    private void detalheVisitanteLogFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_detalheVisitanteLogFocusLost

    }//GEN-LAST:event_detalheVisitanteLogFocusLost

    private void btnBuscaVisitanteLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaVisitanteLogActionPerformed
        Visitante visitante = new Visitante();
        String rg = txtRgVisitanteLog.getText();

        try {
            if(rg != null){

                visitante = VisitanteController.consultarVisitante(rg);

                txtNomeVisitanteLog.setText(visitante.getNome());
                txtRgVisitanteLog.setText(visitante.getRg());

                switch(visitante.getTipoVisitante()){
                    case VISITANTE:
                    cboxTipoVisitanteLog.setSelectedIndex(1);
                    break;
                    case PRESTADORSERVICO:
                    cboxTipoVisitanteLog.setSelectedIndex(2);
                    break;
                    default:
                    cboxTipoVisitanteLog.setSelectedIndex(0);
                    break;
                }
            }
            else
            throw new Exception("para fazer a busca, precisa do rg do visitante");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscaVisitanteLogActionPerformed

    private void cboxTipoVisitanteLogItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxTipoVisitanteLogItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxTipoVisitanteLogItemStateChanged

    private void txtNomeVisitanteLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeVisitanteLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeVisitanteLogActionPerformed

    private void txtNomeVisitanteLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeVisitanteLogMouseClicked

    }//GEN-LAST:event_txtNomeVisitanteLogMouseClicked

    private void txtNomeVisitanteLogFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeVisitanteLogFocusLost

    }//GEN-LAST:event_txtNomeVisitanteLogFocusLost

    private void txtNomeMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMoradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMoradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SCFP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SCFP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SCFP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SCFP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                try {
                    new SCFP().setVisible(true);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
    }

    
    private void carregaCbBloco() {
        cboxBloco.removeAllItems();
        try {            
            for (String item : DAOBloco.buscaBlocos()) {
                cboxBloco.addItem(item);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaVisitanteLog;
    private javax.swing.JButton btnLiberarVisitante;
    private javax.swing.JComboBox<String> cboxBloco;
    private javax.swing.JComboBox<String> cboxTipoVisitanteLog;
    private javax.swing.JTextArea detalheVisitanteLog;
    private javax.swing.JTable gridLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem menuCadastroFuncionario;
    private javax.swing.JMenuItem menuCadastroMorador;
    private javax.swing.JMenuItem menuCadastroVisitante;
    private javax.swing.JTextField txtNomeMorador;
    private javax.swing.JTextField txtNomeVisitanteLog;
    private javax.swing.JTextField txtRgVisitanteLog;
    private javax.swing.JTextField txtnAptLog;
    // End of variables declaration//GEN-END:variables

    private void carregaJTable() throws Exception {                        
        DefaultTableModel model = (DefaultTableModel)gridLog.getModel();                
        SimpleDateFormat hora = new SimpleDateFormat("HH:mm:ss - dd/MM/yyyy");
        
        Object[] dados = null;
        for(LogEntrada dado : DAOLogEntrada.consultaLogEntradaDia(new Date())){
            dados = new Object[]{dado.getVisitante().getNome(),dado.getDescricaoAcao(),String.format("%s",hora.format(dado.getDataEntrada())),String.format("%s - %s",dado.getaVisitar().getBloco(),dado.getaVisitar().getnApt())};
            model.addRow(dados);
        }                
    }
}
